### ISSUE TITLE
This is fantastic 

### ISSUE THREAD

**Issue by bseddy** [dbean104/ff9-rope-jump#1]
No issue, but I didn't know of another way to communicate my gratitude. Thank you so much! I spent all night on my windows box trying to get septomor's code to work it only to find out it doesn't work with the recent versions of Remote Play, specifically version 5.5+. It is no longer possible to install version Remote Play 5.0 or lower on Windows. However, it is possible on Mac. Your code works perfectly, and your README was great at guiding me through how to set it up. After about 7 attempts I got over 1000 jumps!!! I had to borrow my wife's macbook after i saw your github page, but I'm so glad I stumbled upon this! Thank you!!!!!!

**Comment by dbean104** [comment]
Thanks for taking the time to leave a message! I'm glad I could help somebody else get this trophy.
